### ISSUE TITLE
add Discord link

### ISSUE THREAD

**Issue by xhliu** [sCrypt-Inc/sCrypt-Inc.github.io#3]
![image](https://user-images.githubusercontent.com/1017252/163437864-490f5b13-a8c6-4910-a59d-f48afe2fdfec.png)

**Comment by msinkec** [comment]
Done in [d4d4eb5](https://github.com/sCrypt-Inc/sCrypt-Inc.github.io/commit/d4d4eb572b5aa3c506b209266157b2b1b7bae911)
